% GSA code v1.1.
% Generated by Esmat Rashedi, 2010. 
% "	E. Rashedi, H. Nezamabadi-pour and S. Saryazdi,
%“GSA: A Gravitational Search Algorithm”, Information sciences, vol. 179,
%no. 13, pp. 2232-2248, 2009."
%
% This function gives boundaries and dimension of search space for test functions.
function [down,up,dim]=test_functions_range(F_index)

%If lower bounds of dimensions are the same, then 'down' is a value.
%Otherwise, 'down' is a vector that shows the lower bound of each dimension.
%This is also true for upper bounds of dimensions.

%Insert your own boundaries with a new F_index.

dim=30;
if F_index==1
    down=-5;up=10;
end

if F_index==2
    down=-5.12;up=5.12;
end

if F_index==3
    down=-32.768;up=32.768;
end

if F_index==4
    down=-500;up=500;
end

if F_index==5
    down=-100;up=100;
end

if F_index==6
    down=-2;up=2;
end