% GSA code v1.1.
% Generated by Esmat Rashedi, 2010. 
% "	E. Rashedi, H. Nezamabadi-pour and S. Saryazdi,
%“GSA: A Gravitational Search Algorithm”, Information sciences, vol. 179,
%no. 13, pp. 2232-2248, 2009."
%
% This function calculates the value of the objective function.
function fit=test_functions(L,F_index,dim)

%Insert your own objective function with a new F_index.

if F_index==1 %ROSENBROCK
    fit=sum(100*(L(2:dim)-(L(1:dim-1).^2)).^2+(L(1:dim-1)-1).^2);
end

if F_index==2 %RASTRIGIN
    fit=sum(L.^2-10*cos(2*pi.*L))+10*dim;
end

if F_index==3 %ACKLEY
    fit=-20*exp(-.2*sqrt(sum(L.^2)/dim))-exp(sum(cos(2*pi.*L))/dim)+20+exp(1);
end

if F_index==4 %SCHWEFEL
    fit=sum(-L.*sin(sqrt(abs(L))));
end

if F_index==5 %SCHAFFER 2
    fit= 0.5 + ( (power(sin(L(1:1)^2 - L(2:2)^2),2)-0.5) / ((L(1:1)^2 + L(2:2)^2)^2) );
end

if F_index==5 %WEIERSTRASS 
    fit=0;
end










function y=Ufun(x,a,k,m)
y=k.*((x-a).^m).*(x>a)+k.*((-x-a).^m).*(x<(-a));
return